### ISSUE TITLE
Doesn't compile on ubuntu 16.04 (missing ao/ao.h)

### ISSUE THREAD

**Issue by powercycle** [gmn/nanotts#1]
g++ -D_PICO_LANG_DIR=\"/usr/share/pico/lang/\" -I. -I./svoxpico -Wall -g -O2 -c src/mmfile.cpp -o objs/mmfile.o 
g++ -D_PICO_LANG_DIR=\"/usr/share/pico/lang/\" -I. -I./svoxpico -Wall -g -O2 -c src/nanotts.cpp -o objs/nanotts.o 
src/nanotts.cpp:32:19: fatal error: ao/ao.h: No such file or directory

**Comment by gohai** [comment]
Same on Fedora 24. Installing `libao libao-devel` helped.

**Comment by powercycle** [comment]
Installing libao-dev resolved it for Ubuntu 14.04.

**Comment by gmn** [comment]
Would it help if I made a non-libao option?  Libao really was simply a bandaid to get audio. I could easily write an alsa driver and attempt to auto-detect system options.. Just some thoughts. Thanks for the infos.

**Comment by gmn** [comment]
Reopening in lieu of looking at other audio driver options, and auto-detection in ./configure script.

**Comment by powercycle** [comment]
Just need to add a reference to load that library far as I'm concerned.  I was only mentioning it so that maybe the directions to build this project could get updated.

**Comment by duhaime** [comment]
On OSX `brew install libao`
